---
# tasks file for fedora

- name: Include Fedora vars
  include_vars:
    file: "../vars/{{ ansible_distribution_version }}.yml"

- name: Add rpmfusion free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Add rpmfusion none free
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install yum packages
  dnf:
    name: "{{ yum_packages }}"
    state: present

- name: Install latest version packages
  dnf:
    name: "{{ lookup('vars', 'yum_' + ansible_distribution_major_version + '_packages') }}"
    state: present

- name: Install RPM fusion packages
  dnf:
    name: "{{ rpmfusion_packages }}"
    state: present

- name: Update and upgrade system
  dnf: name=* state=latest
  tags: update
  ignore_errors: yes

- import_tasks: vscode.yml
- import_tasks: vagrant.yml